# Generated by Django 6.0.6 on 2026-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_count', models.PositiveIntegerField()),
                ('minterms', models.TextField()),
                ('dont_cares', models.TextField(blank=True, default='')),
                ('simplified_expression', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
